### ISSUE TITLE
Consider tagging releases

### ISSUE THREAD

**Issue by spikespaz** [sebastian-de/easyeffects-thinkpad-unsuck#1]
Tank you so much for sharing your preset with us, it has really made my ThinkPad P14S Gen1 sound *much* better.

I use Nix, so I would really appreciate if you tag specific commits whenever you update. I should also get a notification on GitHub when you release an update/fix. Thank you!

**Comment by sebastian-de** [comment]
Hey @spikespaz , I'm glad to hear that you like the preset!
I just pushed two tags, let me know if you need anything else.
